### ISSUE TITLE
Form does not respect Label Column Width

### ISSUE THREAD

**Issue by derrell** [qooxdoo/qxl.dialog#3]
Setting property `labelColumnWidth` does not take effect. The reason is that only the `maxWidth` is set, not `width`, in this code in Form.js:453:
```
      let view = new qxl.dialog.FormRenderer(this._form);
      view.getLayout().setColumnFlex(0, 0);
      view.getLayout().setColumnMaxWidth(0, this.getLabelColumnWidth());
```

An additional line is needed:
```
      view.getLayout().setColumnWidth(0, this.getLabelColumnWidth());
```

which I have verified, not by changing this code here, but with a kludge in the application:

```
      form._formContainer.getChildren()[0]
        .getLayout()
        .setColumnWidth(0, form.getLabelColumnWidth());
```

**Comment by cboulanger** [comment]
Thanks. Can you provide a PR?

**Comment by derrell** [comment]
Yes. I haven't yet set things up to run from the source tree (I'm using the installed package), but when I do I'll PR this change.
